<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags" %>
<c:set var="ctx" value="${pageContext.request.contextPath}"/>

<strong>乐播</strong>
<table class="table table-hover">
    <tr>
        <th class="input-large">字段</th>
        <th class="input-small">类型</th>
        <th>说明</th>
    </tr>
    <tr>
        <td>
            id
        </td>
        <td>
            string
        </td>
        <td>

        </td>
    </tr>
    <tr>
        <td>
            user
        </td>
        <td>
            object
        </td>
        <td>

        </td>
    </tr>
    <tr>
        <td>
            createdAt
        </td>
        <td>
            string
        </td>
        <td>
            该乐播创建时间
        </td>
    </tr>
    <tr>
        <td>
            text
        </td>
        <td>
            string
        </td>
        <td>
            描述
        </td>
    </tr>
    <tr>
        <td>
            files
        </td>
        <td>
            array
        </td>
        <td>
            第1个是视频，第2个是图片
        </td>
    </tr>
    <tr>
        <td>
            source
        </td>
        <td>
            string
        </td>
        <td>
            来源：android客户端、ios客户端
        </td>
    </tr>
    <tr>
        <td>
            favorited
        </td>
        <td>
            boolean
        </td>
        <td>
            该条乐播是否已被当前登录用户收藏
        </td>
    </tr>
    <tr>
        <td>
            reposted
        </td>
        <td>
            boolean
        </td>
        <td>
            该条乐播是否已被当前登录用户转发
        </td>
    </tr>
    <tr>
        <td>
            favoritesCount
        </td>
        <td>
            int32
        </td>
        <td>
            收藏数
        </td>
    </tr>

    <tr>
        <td>
            repostsCount
        </td>
        <td>
            int32
        </td>
        <td>
            转发数
        </td>
    </tr>
    <tr>
        <td>
            commentsCount
        </td>
        <td>
            int32
        </td>
        <td>
            评论数
        </td>
    </tr>
    <tr>
        <td>
            viewCount
        </td>
        <td>
            int32
        </td>
        <td>
            播放数
        </td>
    </tr>
    <tr>
        <td>
            originStatus
        </td>
        <td>
            object
        </td>
        <td>
            原始乐播，当该乐播是转发的才有值
        </td>
    </tr>
    <tr>
        <td>
            comments
        </td>
        <td>
            array
        </td>
        <td>
            前3条评论
        </td>
    </tr>
    <tr>
        <td>
            userMentions
        </td>
        <td>
            array
        </td>
        <td>
            提到的用户
        </td>
    </tr>
    <tr>
        <td>
            digest
        </td>
        <td>
            boolean
        </td>
        <td>
            是否已被加精
        </td>
    </tr>
</table>

<strong>用户</strong>
<table class="table table-hover">
    <tr>
        <th class="input-large">字段</th>
        <th class="input-small">类型</th>
        <th>说明</th>
    </tr>
    <tr>
        <td>
            id
        </td>
        <td>
            string
        </td>
        <td>

        </td>
    </tr>
    <tr>
        <td>
            screenName
        </td>
        <td>
            string
        </td>
        <td>
            唯一的显示名
        </td>
    </tr>
    <tr>
        <td>
            description
        </td>
        <td>
            string
        </td>
        <td>
            用户个性签名
        </td>
    </tr>
    <tr>
        <td>
            profileImageUrl
        </td>
        <td>
            string
        </td>
        <td>
            用户头像，可能以http开头，也可能以/开头，客户端需判断如果以/开头，则组装成完整URL
        </td>
    </tr>
    <tr>
        <td>
            createdAt
        </td>
        <td>
            string
        </td>
        <td>
            该用户创建时间
        </td>
    </tr>
    <tr>
        <td>
            following
        </td>
        <td>
            boolean
        </td>
        <td>
            当前登录用户是否正在关注该用户
        </td>
    </tr>
    <tr>
        <td>
            followersCount
        </td>
        <td>
            int32
        </td>
        <td>
            粉丝数
        </td>
    </tr>
    <tr>
        <td>
            friendsCount
        </td>
        <td>
            int32
        </td>
        <td>
            关注数
        </td>
    </tr>
    <tr>
        <td>
            favoritesCount
        </td>
        <td>
            int32
        </td>
        <td>
            喜欢数
        </td>
    </tr>
    <tr>
        <td>
            statusesCount
        </td>
        <td>
            int32
        </td>
        <td>
            乐播数
        </td>
    </tr>

    <tr>
        <td>
            beFavoritedCount
        </td>
        <td>
            int32
        </td>
        <td>
            该用户发布的乐播被收藏的次数
        </td>
    </tr>
    <tr>
        <td>
            viewCount
        </td>
        <td>
            int32
        </td>
        <td>
            该用户发布的乐播被播放的次数
        </td>
    </tr>
    <tr>
        <td>
            weiboVerified
        </td>
        <td>
            boolean
        </td>
        <td>
            是否是新浪微博认证用户，即加V用户
        </td>
    </tr>
    <tr>
        <td>
            blocking
        </td>
        <td>
            boolean
        </td>
        <td>
            当前登录用户是否已将该用户加入黑名单
        </td>
    </tr>
</table>

<strong>error</strong>

<p><code>200&lt;=HTTP状态码<300为成功，否则失败</code></p>

<p><code>HTTP状态码>=400并且内容为JSON，是错误对象</code></p>
<ul>
    <li>
        0
        <ul>
            <li>是某些客户端默认值，不是服务端返回的，客户端无法连接到服务端时可能会得到这个值</li>
        </ul>
    </li>
    <li>
        1xx - 消息
        <ul>
            <li>不会返回此类状态码</li>
        </ul>
    </li>
    <li>
        2xx - 成功
        <ul>
            <li>除非特别说明，服务端处理成功，响应HTTP状态码<code>200</code></li>
            <li>极少情况，服务端处理成功，也可能响应2xx(非200)。如果某接口属于这种情况，服务端会协助客户端正确处理，并在接口文档中写清楚</li>
        </ul>
    </li>
    <li>3xx - 重定向
        <ul>
            <li>客户端应该支持重定向</li>
        </ul>
    </li>
    <li>4xx -请求错误
        <ul>
            <li>如果服务端发生错误，HTTP状态码一定<code>>=400</code></li>
            <li>如果HTTP状态码>=400，那么一定发生了错误</li>
            <li>如果HTTP状态码>=400，并且内容是JSON，那么内容<code>一定</code>是错误对象</li>
        </ul>
    </li>
    <li>5xx - 服务器错误</li>
</ul>

<table class="table table-hover">
    <tr>
        <th class="input-medium">HTTP状态码</th>
        <th class="input-medium">code</th>
        <th class="input-medium">message</th>
        <th>说明</th>
    </tr>
    <tr>
        <td>
            400
        </td>
        <td>
            10400
        </td>
        <td>
            Bad Request
        </td>
        <td>

        </td>
    </tr>
    <tr>
        <td>
            401
        </td>
        <td>
            10401
        </td>
        <td>
            Unauthorized
        </td>
        <td>

        </td>
    </tr>
    <tr>
        <td>
            403
        </td>
        <td>
            10403
        </td>
        <td>
            Forbidden
        </td>
        <td>

        </td>
    </tr>
    <tr>
        <td>
            404
        </td>
        <td>
            10404
        </td>
        <td>
            Not Found
        </td>
        <td>
            按ID查询某个对象时，未找到，可能已被删除
        </td>
    </tr>
    <tr>
        <td>
            400
        </td>
        <td>
            10427
        </td>
        <td>
            Duplicate
        </td>
        <td>
            重复的操作，违反业务规则
        </td>
    </tr>
    <tr>
        <td>
            400
        </td>
        <td>
            10428
        </td>
        <td>

        </td>
        <td>
            不能关注该用户，因为你在对方的黑名单中
        </td>
    </tr>
    <tr>
        <td>
            400
        </td>
        <td>
            10429
        </td>
        <td>

        </td>
        <td>
            不能关注该用户，因为对方在你的黑名单中
        </td>
    </tr>
    <tr>
        <td>
            500
        </td>
        <td>
            10500
        </td>
        <td>
            Internal Server Error
        </td>
        <td>

        </td>
    </tr>
</table>