<%@ page contentType="text/html;charset=UTF-8" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="tags" tagdir="/WEB-INF/tags" %>
<c:set var="ctx" value="${pageContext.request.contextPath}"/>

<strong>乐播</strong>
<table class="table table-hover">
    <tr>
        <th class="input-large">字段</th>
        <th class="input-small">类型</th>
        <th>说明</th>
    </tr>
    <tr>
        <td>
            id
        </td>
        <td>
            string
        </td>
        <td>

        </td>
    </tr>
    <tr>
        <td>
            user
        </td>
        <td>
            object
        </td>
        <td>

        </td>
    </tr>
    <tr>
        <td>
            createdAt
        </td>
        <td>
            string
        </td>
        <td>
            该乐播创建时间
        </td>
    </tr>
    <tr>
        <td>
            text
        </td>
        <td>
            string
        </td>
        <td>
            描述
        </td>
    </tr>
    <tr>
        <td>
            files
        </td>
        <td>
            array
        </td>
        <td>
            第1个是视频，第2个是图片
        </td>
    </tr>
    <tr>
        <td>
            source
        </td>
        <td>
            string
        </td>
        <td>
            来源：android客户端、ios客户端
        </td>
    </tr>
    <tr>
        <td>
            favorited
        </td>
        <td>
            boolean
        </td>
        <td>
            该条乐播是否已被当前登录用户收藏
        </td>
    </tr>
    <tr>
        <td>
            reposted
        </td>
        <td>
            boolean
        </td>
        <td>
            该条乐播是否已被当前登录用户转发
        </td>
    </tr>
    <tr>
        <td>
            favoritesCount
        </td>
        <td>
            int32
        </td>
        <td>
            收藏数
        </td>
    </tr>

    <tr>
        <td>
            repostsCount
        </td>
        <td>
            int32
        </td>
        <td>
            转发数
        </td>
    </tr>
    <tr>
        <td>
            commentsCount
        </td>
        <td>
            int32
        </td>
        <td>
            评论数
        </td>
    </tr>
    <tr>
        <td>
            viewsCount
        </td>
        <td>
            int32
        </td>
        <td>
            播放数
        </td>
    </tr>
    <tr>
        <td>
            originStatus
        </td>
        <td>
            object
        </td>
        <td>
            原始乐播，当该乐播是转发的才有值
        </td>
    </tr>
</table>

<strong>用户</strong>
<table class="table table-hover">
    <tr>
        <th class="input-large">字段</th>
        <th class="input-small">类型</th>
        <th>说明</th>
    </tr>
    <tr>
        <td>
            id
        </td>
        <td>
            string
        </td>
        <td>

        </td>
    </tr>
    <tr>
        <td>
            screenName
        </td>
        <td>
            string
        </td>
        <td>
            唯一的显示名
        </td>
    </tr>
    <tr>
        <td>
            profileImageUrl
        </td>
        <td>
            string
        </td>
        <td>
            用户头像，可能以http开头，也可能以/开头，客户端需判断如果以/开头，则组装成完整URL
        </td>
    </tr>
    <tr>
        <td>
            createdAt
        </td>
        <td>
            string
        </td>
        <td>
            该用户创建时间
        </td>
    </tr>
    <tr>
        <td>
            following
        </td>
        <td>
            boolean
        </td>
        <td>
            当前登录用户是否正在关注该用户
        </td>
    </tr>
    <tr>
        <td>
            followersCount
        </td>
        <td>
            int32
        </td>
        <td>
            粉丝数
        </td>
    </tr>
    <tr>
        <td>
            friendsCount
        </td>
        <td>
            int32
        </td>
        <td>
            关注数
        </td>
    </tr>
    <tr>
        <td>
            favoritesCount
        </td>
        <td>
            int32
        </td>
        <td>
            喜欢数
        </td>
    </tr>
    <tr>
        <td>
            statusesCount
        </td>
        <td>
            int32
        </td>
        <td>
            乐播数
        </td>
    </tr>

    <tr>
        <td>
            beFavoritedCount
        </td>
        <td>
            int32
        </td>
        <td>
            该用户发布的乐播被收藏的次数
        </td>
    </tr>
    <tr>
        <td>
            viewsCount
        </td>
        <td>
            int32
        </td>
        <td>
            该用户发布的乐播被播放的次数
        </td>
    </tr>
</table>

<strong>error</strong>
<table class="table table-hover">
    <tr>
        <th class="input-large">code</th>
        <th class="input-large">message</th>
        <th>说明</th>
    </tr>
    <tr>
        <td>
            400
        </td>
        <td>
            Bad Request
        </td>
        <td>

        </td>
    </tr>
    <tr>
        <td>
            401
        </td>
        <td>
            Unauthorized
        </td>
        <td>

        </td>
    </tr>
    <tr>
        <td>
            403
        </td>
        <td>
            Forbidden
        </td>
        <td>

        </td>
    </tr>
    <tr>
        <td>
            404
        </td>
        <td>
            Not Found
        </td>
        <td>
            接口地址不正确
        </td>
    </tr>
    <tr>
        <td>
            427
        </td>
        <td>
            Duplicate
        </td>
        <td>
            重复的操作，违反业务规则
        </td>
    </tr>
    <tr>
        <td>
            428
        </td>
        <td>

        </td>
        <td>
            不能关注该用户，因为你在对方的黑名单中
        </td>
    </tr>
    <tr>
        <td>
            429
        </td>
        <td>

        </td>
        <td>
            不能关注该用户，因为对方在你的黑名单中
        </td>
    </tr>
    <tr>
        <td>
            500
        </td>
        <td>
            Internal Server Error
        </td>
        <td>

        </td>
    </tr>
</table>